apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  type: NodePort
  selector:
    app: portainer
  ports:
  - name: https
    port: 9443
    targetPort: 9443
    nodePort: 9443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer
spec:
  replicas: 1
  selector:
    matchLabels: { app: portainer }
  template:
    metadata:
      labels: { app: portainer }
    spec:
      serviceAccountName: default
      containers:
      - name: portainer
        image: portainer/portainer-ce:2.21.5
        args: ["-H", "unix:///var/run/docker.sock"]
        ports:
        - containerPort: 9443
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
